add_newline = false
format = "$directory$git_branch$character"

[line_break]
disabled = true

[character]
success_symbol = "[❯](bold #30e248)"
error_symbol = "[❯](bold #d14040)"

[directory]
truncation_length = 1
truncation_symbol = ""
format = "[$path](#4ab0df) "

[git_branch]
symbol = ""
format = "on [$symbol $branch](bold #30e248) "
