add_newline = false

format = """
$directory$git_branch$nodejs
$character"""

[character]
success_symbol = "[❯](bold #30e248)"
error_symbol = "[❯](bold #d14040)"

[directory]
truncation_length = 100
truncation_symbol = ""
truncate_to_repo = false
format = "[$path](#4ab0df) "

[git_branch]
symbol = ""
format = "on [$symbol $branch](bold #30e248) "

[nodejs]
symbol = ""
style = "bold green"
not_capable_style = "bold red"
format = "via [$symbol ($version)]($style) "
